apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: muchtodo
data:
  APP_ENV: "production"
  PORT: "8080"
  DB_HOST: "mongodb-service"
  DB_PORT: "27017"
  DB_NAME: "muchtodo"
