apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: muchtodo
type: Opaque
data:
  mongodb-uri: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkMTIzQG1vbmdvZGItc2VydmljZToyNzAxNy9tdWNodG9kbz9hdXRoU291cmNlPWFkbWlu
  db-user: YWRtaW4=
  db-password: cGFzc3dvcmQxMjM=
